### ISSUE TITLE
"The page you were looking for doesn't exist."

### ISSUE THREAD

**Issue by hugovk** [sarahhodne/travis-lite#21]
First, Travis Lite is really handy to check the build status on my phone, thanks!

The list of repos on the homepage or a user's page show the last coloured build status fine:

http://travis-lite.com/
http://travis-lite.com/ramitos

But when clicking to a project or build:

http://travis-lite.com/ramitos/domain.js
http://travis-lite.com/ramitos/domain.js/builds/21521400

There's an error:

> **The page you were looking for doesn't exist.**
> 
> You may have mistyped the address or the page may have moved.
> 
> If you are the application owner check the logs for more information.

**Comment by sarahhodne** [comment]
I think this is because Rails recognizes the ".js" as a filetype extension instead of a part of the repository name and is therefore looking for a `ramitos/domain` using a JavaScript filetype instead of `ramitos/domain.js`.

I'm not really maintaining travis-lite anymore, but if anyone wants to take a look at this, I'm happy to review and merge the PR.

**Comment by hugovk** [comment]
That .js repo just happened to be at the top, the problem seems to happen with all repos with dots in them, and also the individual build logs.

More examples. These work:

http://travis-lite.com/github
http://travis-lite.com/github/linguist
http://travis-lite.com/github/maven-plugins

Don't work:
http://travis-lite.com/github/linguist/builds/21611099
http://travis-lite.com/github/maven-plugins/builds/15185216
http://travis-lite.com/github/developer.github.com
http://travis-lite.com/github/government.github.com
